version: "3.9"

services:
  mobile_backend:
    image: ghcr.io/averagefun/smarthome/mobile-backend:primary
    build: "MobileBackend"
    platform: "linux/amd64"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis

  emulation_backend:
    image: ghcr.io/averagefun/smarthome/emulation-backend:primary
    build: "Emulation"
    platform: "linux/amd64"
    ports:
      - "8090:8090"
    depends_on:
      - redis

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=smarthome
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    command: redis-server
    volumes:
      - redis_data:/var/lib/redis
      - redis_config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"

  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/var/lib/clickhouse

volumes:
  postgres_data:
  redis_data:
  redis_config:
  clickhouse_data:
